.travis.yml

Adding simple configuration file that runs targets defined in Makefile.

Run Travis-CI

---

.gitignore
package.json
yarn.lock

This is a preparation of code coverage reports to be ingested by services integrated with GitHub.

Code coverage

---

.eslintignore
.eslintrc.json
.gitignore
Makefile
config/customEnvironmentVariables.yml
examples/test-app/app.js
examples/test-app/includes/header.njk
examples/test-app/steps/HelloWorld.js
examples/test-app/views/HelloWorld.html
package.json
src/Journey.js
src/errors/expectImplemented.js
src/main.js
src/services/sessions.js
src/steps/BaseStep.js
src/steps/Page.js
src/util/isTest.js
templates/patterns/header.njk
test/.eslintrc.json
test/Journey.test.js
test/steps/BaseStep.test.js
test/steps/Page.test.js
test/util/chai.js
test/util/supertest.js
yarn.lock

This PR improves the code quality by conforming to the standard set by [@hmcts/eslint-config](https://github.com/hmcts/eslint-config).

Lint things

---

.gitignore
.travis.yml
Makefile
package.json
yarn.lock

This change also replaces istanbul with nyc.

Code coverage: integrate with Codecov

---

examples/test-app/app.js
examples/test-app/steps/Country.js
examples/test-app/steps/Entry.js
examples/test-app/steps/ExitNorthernIreland.js
examples/test-app/steps/Name.js
examples/test-app/steps/Start.js
examples/test-app/views/Country.html
examples/test-app/views/ExitNorthernIreland.html
examples/test-app/views/Start.html
src/Journey.js
src/main.js
src/middleware/createSession.js
src/services/flow.js
src/steps/BaseStep.js
src/steps/EntryPoint.js
src/steps/Question.js
src/steps/Redirect.js
test/Journey.test.js
test/middleware/createSession.test.js
test/services/flow.test.js
test/steps/EntryPoint.test.js
test/steps/Question.test.js
test/steps/Redirect.test.js
test/util/supertest.js

This PR adds new branching logic that can be used to send users down different paths depending on answers they give.
The example in [examples/test-app/steps/Country.js](https://github.com/hmcts/one-per-page/blob/b0c6257302e5169b257c614f46e1f31470a21f80/examples/test-app/steps/Country.js) shows this logic in usage:
```
class Country extends Question {
get url() {
return '/country';
}
get form() {
return form(field('country'));
}
next() {
const livesInNI = () => this.fields.country.value === 'northern-ireland';
return branch(
goTo(this.journey.ExitNorthernIreland).if(livesInNI),
goTo(this.journey.Name)
);
}
}
```

Branching flow

---

examples/test-app/package.json
examples/test-app/steps/Country.js
examples/test-app/steps/Name.js
examples/test-app/utils/validators.js
examples/test-app/views/Country.html
examples/test-app/views/Name.html
examples/test-app/yarn.lock
src/middleware/parseRequest.js
src/services/fields.js
src/steps/Question.js
test/middleware/parseRequest.test.js
test/services/fields.test.js
test/steps/Question.test.js
test/util/supertest.js
test/views/question_views/simpleQuestion.html

Question validation

---

package.json

Update i18next to version 10.0.1

---

examples/test-app/app.js
examples/test-app/assets/js/.eslintrc.json
examples/test-app/assets/js/main.js
examples/test-app/package.json
examples/test-app/steps/Contact.content.en.json
examples/test-app/steps/Contact.step.js
examples/test-app/steps/Contact.template.html
examples/test-app/steps/Country.step.js
examples/test-app/steps/Start.template.html
examples/test-app/yarn.lock

This PR demonstrates using https://github.com/hmcts/look-and-feel/pull/26 to import files from govuk_frontend_toolkit.

Expose JS from govuk_frontend_toolkit

---

README.md
examples/test-app/README.md

This pull request is to steamline the documentation so its easier for new starters to understand how to get the application up and running.

update the documentation while going through as a new starter

---

docs/steps/Interstitial.md
examples/test-app/app.js
examples/test-app/steps/DateOfMarriage.step.js
examples/test-app/steps/InfoPage.step.js
examples/test-app/steps/InfoPage.template.html
src/flow/RequestBoundJourney.js
src/flow/index.js
src/flow/treeWalker.js
src/steps/Interstitial.js
src/steps/check-your-answers/CheckYourAnswers.js
src/steps/index.js
test/flow/RequestBoundJourney.test.js
test/flow/treeWalker.test.js
test/steps/Interstitial.test.js
test/steps/check-your-answers/CheckYourAnswers.test.js

This PR adds a new step type, Intersitials, which are pages that can be dropped in between questions.

Interstitial steps

---

src/i18n/loadStepContent.js

Enables a common.json content file to be used.
No each app can have a /common/content.json to declare common content for templates

add common content.json to content of step

---

src/i18n/contentProxy.js
test/i18n/contentProxy.test.js

Ddefault language when getting keys from the content proxy

Default language for content proxy

---

src/session/index.js
src/session/sessionStoreSerializer.js
src/util/crypto.js
test/session/sessionStoreSerializer.test.js
test/session/sessions.test.js
test/util/crypto.test.js

Add ability to encrypt session at rest

Add session encryption

---

src/steps/Question.js

Latest changes are causing tests to fail as no settings set on our journey yet

only look for useCsrfToken if settings is there

---

README.md
package.json
src/forms/fields.js
test/forms/fields.test.js

Reverts hmcts/one-per-page#146

Revert "List object values"

---

examples/test-app/app.js
examples/test-app/steps/DateOfMarriage.content.en.json
examples/test-app/steps/DateOfMarriage.step.js
package.json
src/flow/journey.js
src/i18n/i18Next.js
test/i18n/i18Next.test.js

add ability to add filters to content files and execute the same as in nunjucks template.
For example in content files you can now do this `{{ '2001-10-02T00:00:00.000Z' | date }}` as you would the same in nunjucks

Filters is content files

---

package.json
src/flow/action.js
src/steps/EntryPoint.js
src/steps/Redirect.js

Pass next up the chain so that `action` can call it.

on redirect pass next() callback

---

package-lock.json
package.json
yarn.lock

Updating dependencies brings vulnerabilities from:
_84 vulnerabilities found - Packages audited: 8803
Severity: 12 Low | 60 Moderate | 11 High | 1 Critical_
to:
_21 vulnerabilities found - Packages audited: 8811
Severity: 12 Low | 9 Moderate_

Updated dependencies to remove any high or critical vulnerabilities

---

package.json
src/flow/RequestBoundJourney.js
test/flow/RequestBoundJourney.test.js

Content was loading intermittently, so modified middleware so it will always wait to load.

load step content in middleware not promise

---

package.json
src/middleware/sanitizeRequestBody.js
src/steps/Question.js
test/middleware/sanitizeRequestBody.test.js
yarn.lock

[DIV-3859 - cross site scripting is possible on AOS and DN Journeys](https://tools.hmcts.net/jira/browse/DIV-3859)
Cross site scripting is not handled in One Per Page.
This PR adds a middleware to sanitise all data sent in a post request to the question step.

Sanitise request body on question step

---

package.json

Update to 4.1.4, the latest release.

---

package.json
src/forms/filledForm.js
src/util/watches.js
test/forms/filledForm.test.js
test/util/watches.test.js

Add ability to watch session properties and remove data. For example:
```
const SimpleQuestion = class extends Question {
get form() {
return form({ name: text });
}
get template() {
return 'question_views/simpleQuestion';
}
next() {
return goTo({ path: '/next-step' });
}
};
const SimpleQuestion2 = class extends Question {
get watches() {
return {
'SimpleQuestion.name': (previousValue, currentValue, remove) => {
remove('SimpleQuestion2.name');
}
};
}
get form() {
return form({ name: text });
}
get template() {
return 'question_views/simpleQuestion';
}
next() {
return goTo({ path: '/next-step' });
}
};
```

Add watch ability

---

src/session/index.js

Add a default retry strategy as well
Fixes https://github.com/hmcts/one-per-page/pull/191

Add continuous ping to prevent connection going idle
