- Dockerfile
With this change:
- yarn install/add/upgrade etc will target /usr/src/node_modules
- make build will update the node_modules if the yarn.lock is changed
This means that if you are inside the container and need to install a
new package you can just run `yarn add` and not worry about it creating
a node_modules folder owned by root that will be mirrored back to your
host machine.
Also it means that for users of Docker for Mac, which has a well known
issue with slow file access on nfs mounts, yarn will be as fast as it
would be locally. Before this change a `yarn install` could take 3-4
mins and an `npm install` could take 15 mins.
NOTE: I've had to first copy the package.json and yarn.lock in to
`/usr/src/` as yarn doesn't support the creation of `.bin` folders in
the modules-folder path …
> Update dockerfile to make yarn install outside of the app folder

- config/custom-environment-variables.yml
- config/testing.yml
- docker-compose.yml
- examples/test-app/app.js
- examples/test-app/config/custom-environment-variables.yml
- examples/test-app/config/default.yml
- examples/test-app/steps/CreateSession.js
- examples/test-app/steps/Sessions.js
- examples/test-app/views/HelloWorld.html
- package.json
- src/Journey.js
- src/main.js
- src/services/sessions.js
- src/services/sessions/shims.js
- test/Journey.test.js
- test/services/sessions.test.js
- test/util/chai.js
- test/util/supertest.js
- yarn.lock
This PR adds simple session management using express session, with some extra functionality implemented by shimming the functions on the `req.session` and `req.sessionStore`.
Goals for sessions:
- -Ability to explicitly create a session- - Complete, provided by `req.session.generate()`
- Middleware / Step to create a session - todo
- -Ability to enforce that a session- - Complete, provided by `req.session.active()`
- Middleware to enforce a session - todo
- Middleware / Exit step to destroy a session - todo
- Per record encryption - to do
> Simple sessions

- examples/test-app/steps/HelloWorld.js
- package.json
- src/Journey.js
- src/main.js
- src/middleware/requireSession.js
- src/services/sessions.js
- src/services/sessions/shims.js
- test/Journey.test.js
- test/middleware/requireSession.test.js
- test/util/chai.js
- test/util/supertest.js
- yarn.lock
This PR implements the requireSession middleware. It is based off of #13 Simple Sessions.
It can be added to a step to enforce a session on that page. By default it redirects to `/` (TODO: should be configurable with some `startpage` property from Journey or infer from which step is of type Start?). You can override the behaviour by providing a `noSessionHandler` to the journey function.
CreateSession and DestroySession can be created using similar approaches.
> Require session middleware

- docker-compose.yml
- examples/test-app/app.js
- examples/test-app/package.json
- examples/test-app/steps/CreateSession.js
- examples/test-app/steps/HelloWorld.js
- examples/test-app/steps/Name.js
- examples/test-app/views/Name.html
- examples/test-app/yarn.lock
- package.json
- src/main.js
- src/middleware/addLocals.js
- src/middleware/parseRequest.js
- src/services/fields.js
- src/steps/BaseStep.js
- src/steps/Page.js
- src/steps/Question.js
- test/middleware/parseRequest.test.js
- test/services/fields.test.js
- test/steps/BaseStep.test.js
- test/steps/Question.test.js
- test/util/supertest.js
- test/views/question_views/simpleQuestion.html
- yarn.lock
This PR implements a method of declaring specific fields to be parsed and available for validation.
You declare the fields on your Question as so:
```
class Name extends Question {
...
get form() {
return form(
field('firstName'),
field('lastName')
);
}
}
```
These would then be available on the template to render, each with a `.id`, `.name`, `.value`:
```
<form>
<input type="textbox"
id="{{fields.firstName.id}}"
name="{{fields.firstName.name}}"
value="{{fields.firstName.value}}">
</form>
```
For convenience we are building some helpers in https://github.com/hmcts/look-and-feel that use this field structure:
```
{% from "look-and-feel/components/fields.njk" import textbox %}
<form>
{{ textbox(fields.firstName, "First name(s)", hint="Include all middle names here") }}
</form>
```
> Fields: parsing and storing in the session

- examples/test-app/steps/Country/index.js
- src/util/walkMap.js
- test/middleware/applyContent.test.js
- test/middleware/destroySession.test.js
- test/middleware/parseRequest.test.js
- test/services/fields.test.js
- test/services/sessions.test.js
This PR fixes up linting issues that were introduced by #26, #25 and #23.
These issues were not noticed by the team when they were merged due to codacy deciding not to build the repo once ownership was transferred from me to @jenkins-reform-hmcts. Codacy needs the owner to have commited to the repo.
In [src/util/walkMap.js](https://github.com/hmcts/one-per-page/blob/6f0d5f12e0b1ea40ac1ee281946e3217a8d7a449/src/util/walkMap.js) I have ignored linting rather than fixing the issues. This is because I would rather use an [es6 proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to control access to the content instead of running through every key in the content to build a map of all the content. This is very computationally expensive ( between O(2n^2) …
> Fix linting issues introduced in recent PRs

- examples/test-app/steps/respondent/RespondentName.content.en.json
- examples/test-app/steps/respondent/RespondentName.step.js
- src/steps/Page.js
- test/steps/Page.test.js
This PR fixes a bug found in the step function locals where we don't properly bind the function to the step. The result is that `this` refers to the locals object and not the step, which causes problems if you refer to this in a function. 
This bug doesn't appear in getters, only functions.
_example:_
```
class MyStep extends Question {
fullUrl() {
return `${ this.journey.baseUrl }/${ this.url }`;
}
}
```
When called in the template, `this` wouldn't have `journey` defined on it due to `this` being the locals object we build to pass to express for rendering.
> Bind functions to the step when exposing them to locals

- LICENSE.md
Just noticed this was missing when looking in the hmcts github repo list
> Add the MIT Licenses file

- src/flow/treeWalker.js
Trampolines are a way of doing recursion when your language doesn't support
tail call optimisation. Standard recursion would lead to the stack growing
to overflow.
Instead we use the trampoline to bounce the stack. It executes the iterate
function of the TreeWalker it's given. If that TreeWalker returns a
TreeWalker it will continue executing them until a result is returned.
This concept wasn't obvious from the code so I've added this as a comment above the trampoline function.
For more reading on trampolines, this blog is pretty good:
http://raganwald.com/2013/03/28/trampolines-in-javascript.html
> Document what a trampoline is as it's not an obvious concept

- examples/test-app/app.js
- examples/test-app/steps/CheckYourAnswers.content.en.json
- examples/test-app/steps/CheckYourAnswers.template.html
- examples/test-app/steps/Contact.template.html
- examples/test-app/steps/Country.content.json
- examples/test-app/steps/Country.template.html
- examples/test-app/steps/Name.template.html
- examples/test-app/steps/Start.template.html
- examples/test-app/steps/respondent/RespondentTitle.template.html
- examples/test-app/views/question-globals.njk
This PR demonstrates how globals and multiple extends can be used to clean up templates.
**Globals**
Any variables defined in `nunjucks.globals` are available in all templates. This is useful for things that appear on all templates like the phase, service name or the feedback link.
```
lookAndFeel.configure(app, {
...
nunjucks: {
globals: {
phase: 'ALPHA',
feedbackLink: 'https://github.com/hmcts/one-per-page/issues/new'
}
}
...
});
```
**Multiple extends**
You can extend more than one template in your templates. The last extend will provide the document root. 
This means that you need to put the layout you want to extend last and any extends before this can only set variables and implement blocks. 
The blocks in those earlier extends will override the default blocks set in the layout. You …
> Demonstrate using globals in templating

- examples/test-app/app.js
- examples/test-app/package.json
- examples/test-app/steps/DateOfMarriage.content.en.json
- examples/test-app/steps/DateOfMarriage.step.js
- examples/test-app/steps/DateOfMarriage.template.html
- examples/test-app/steps/Entry.step.js
- examples/test-app/steps/exits/ExitDate.content.json
- examples/test-app/steps/exits/ExitDate.step.js
- examples/test-app/steps/exits/ExitDate.template.html
- examples/test-app/yarn.lock
- src/forms/complex/dateField.js
- src/forms/compoundField.js
- src/forms/field.js
- src/forms/fieldParsers.js
- src/forms/form.js
- src/forms/index.js
- src/forms/simpleFields.js
- src/util/checks.js
- test/forms/compoundField.test.js
- test/forms/field.test.js
- test/forms/fieldParsers.test.js
This PR adds a new base field class, the CompoundField, which can be used to collect mutliple fields and map them to one value.
In the demo app we use this to capture a date.
**Compound validations**
In compound fields you may want to validate the whole object but attach errors to specific fields inside the compound. To do this you can provide an `errorFor` instead of an error message as the first argument to validation functions (like `joi`). The first argument of `errorFor` indicates which subfield the error should be attached to and the second is the error mesage.
```
compoundField('date',
textField('day'),
textField('month'),
textField('year'),
).joi(
errorFor('day', 'Enter a day'),
Joi.object()
.with('year', 'day')
.with('month', 'day')
)
```
**Mapping the value**
You can map the …
> Compound field

- src/steps/Page.js
This possibly will fix #77. 
#77 details an issue with content not loading correctly. This may fix this issue by ensuring that Pages actually wait for it's promises before handling the request. Pages were not waiting as the middleware that waits was declared in BaseStep and Page was redefining the `middleware` function without including a `super` call.
This would have cascaded to Questions, meaning that whether the content loads was mainly dependent on hoping the request took longer than the promise took to resolve.
I can't :100: guarantee this fixes it but I haven't been able to replicate since this change.
> Fix #77 by always waiting for a promises to complete

- src/steps/Question.js
- test/steps/Question.test.js
Fixes #74.
This PR filters ref fields out of the default values of a step on the basis that they would be included in the values object by the step that captured them. Without this you need to explicitly set the values object on any steps where you use references.
> Filter ref fields out of default values

- CHANGELOG.md
- package.json
- src/forms/fieldValue.js
- src/forms/fields.js
- test/forms/fieldValues/transformFieldValue.test.js
This PR fixes a bug found in 2.0.0 that was caused by renaming the field parameter in TransformFieldValue to wrapped. This meant that cloning the TransformFieldValue would cause it to lose it's wrapped field, which happens when you do something like: `list(convert(..., text))` or `object({ foo: convert(...) })`.
> Fix wrapped

- docs/steps/BaseStep.md
- src/steps/BaseStep.js
- test/steps/BaseStep.test.js
Closes #89 and #87. 
This PR allows developers to set the global and step specific timeouts.
Documentation on how to use this feature is included in the PR and will be available at [Custom step timeouts](https://one-per-page.herokuapp.com/docs/steps/BaseStep#custom-step-timeouts) when merged.
> Allow developers to set custom timeouts

- docs/forms/field-types.md
- examples/test-app/steps/Name.step.js
- src/forms/fields.js
- test/forms/fields.test.js
Feedback from SSCS has highlighted that the way of using `ref`, where you wrap a field with it, is confusing.
The reason behind it is that the ref uses the name of the field in the form to load from the other step. Which requires that both fields are named the same in both steps.
Where this breaks down is where you have a field captured multiple times on different steps with different context and want to refer to them in the same step:
```js
class PetitionerDetails extends Question {
get form() {
return form({
name: text,
dob: date
});
}
}
class RespondentDetails extends Question {
get form() {
return form({
name: text,
dob: date
});
}
}
class ReferringToOthers extends Question {
get form() {
return form({
petitionerName: ref(this.journey.steps.PetitionerDetails, text),
respondentName: …
```
> Better refs

- src/steps/check-your-answers/CheckYourAnswers.js
- test/steps/check-your-answers/CheckYourAnswers.test.js
Prior to this change if a user attempted to access Check Your Answers
without a valid session they would get a 500 page. This was due to us
attempting to use the session before Question had required that there
was a session.
> Collect steps after we've required a session exists

- src/forms/filledForm.js
- src/forms/form.js
- src/middleware/preventCaching.js
- src/steps/AddAnother.js
- src/steps/Question.js
- src/steps/check-your-answers/CheckYourAnswers.js
- test/forms/filledForm.test.js
- test/forms/form.test.js
- test/steps/Question.test.js
This PR prevents browsers from caching Questions. This ensures that when a user hits back the browser issues a fresh GET request and so the most up to date values are displayed (as documented in #68).
To do this we have added cache control headers that force a revalidation and changed how questions act under error. If the users input is not valid the answers will be stored in a temporary section in session and a 302 will be issued. The browser will then GET the page again and the users answers will be loaded from temp session and validated. The errors will then be rendered on the page.
This `temp session -> 302 -> GET -> load -> render errors` behaviour is required as if we render the errors on POST and prevent the browser from caching the response then when you hit back the browser will …
> Prevent browsers from caching Questions

- src/forms/fieldValue.js
- test/forms/fieldValues/refValue.test.js
Before this change, having a ref in a step would mean `form.isFilled`
would return true and so validation would be run on first visiting a
page.
Now refs aren't included in this check and so the validation is only
run on subsequent visits.
> Ensure refs aren't included in checking if an answer has been given

- src/util/logging.js
This PR fixes a mistake in how we use the nodejs-logging library if it is found.
> Fix logger

- src/forms/filledForm.js
- src/forms/form.js
- test/forms/filledForm.test.js
This PR ensures that validations are run on empty forms after a POST request.
Before this change if the user didn't enter any values then no error messages would be displayed, since the form would claim to not be filled.
> Ensure forms filled from temp values are validated on GET requests

- examples/test-app/steps/exits/ExitNorthernIreland.step.js
- examples/test-app/steps/exits/ExitNorthernIreland.template.html
- src/flow/index.js
- src/flow/smartRedirector.js
- src/flow/treeWalker.js
- test/flow/smartRedirector.test.js
- test/steps/AddAnother.test.js
- test/steps/EntryPoint.test.js
- test/steps/Redirect.test.js
This PR uses the tree walking introduced by CheckYourAnswers to modify the behaviour of the `goTo` flow control to walk the tree from the next step declared in the `goTo` and find the next step following that path which is not yet complete. 
The existing functionality to `goTo` (always redirect to the given step) persists but has been moved to the new `redirectTo` flow control.
> Clever flow control

- src/flow/smartRedirector.js
This PR narrows the scope of the check for a step not having a flow control, which stops us from suppressing other errors. Before this change if `flowControl.last` failed, for example for an infinite loop, then you would get a confusing "Step does not have a flowControl" error message.
> Stop suppressing errors from the flowControls, such as infinite loops

- package.json
There is a breaking change with the dependency `deepmerge` v2.10, therefore, until
the framework code can be fixed I'm pegging deepmerge at 2.0.1 as this is known to work.
> Peg deepmerge at 2.0.1

- src/session/index.js
- In SYA we have a requirement to have the session age set at 20 minutes.
- Currently you can pass the `maxAge` option to one-per-page. However as per the documentation of express-session, https://github.com/expressjs/session#cookieexpires, what ever is set last between `expires` and `maxAge` will be used. Therefore our `maxAge` option will not be used.
- To fix this: In `session/index.js`, swap the order that the default options and custom options are merged into one, so that the custom options are set last.
> Custom session options

- src/steps/AddAnother.js
- src/steps/Question.js
- test/steps/AddAnother.test.js
- test/steps/Question.test.js
- This is to handle validation errors when using to AJAX to post values within the Add Another class.
- It checks if the request is an AJAX or not and if so build an object that contains the field within `item` and its errors.
- Then send it to the AJAX callback.
This is what is the errors object looks like:
```
{ validationErrors: [{ 
field: 'whatYouDisagreeWith', errors: [Array], value: 'invalid field value' 
}, { 
field: 'reasonForAppealing', errors: [Array], value: 'invalid field value' 
} 
]}
```
- Added the ability to use ajax to get the values of the fields
- Added unit tests for all
> AJAX Validation handling

- src/i18n/contentProxy.js
- This fixes and issue which has occurred when using the delete ajax endpoint. It currently comes up with an error for `maximum call stack exceeded` and it occurs in the contentProxy file. 
- I'm not currently sure why or how it happens but when getting the content, either `observers` or `toJSON` is appended to the object. It continually does this until the error is thrown e.g. `datesCantAttend.fields.error.notEnough.observers.observers.oberservers` etc etc. 
- The fix is to do a similar thing that has been done previously for `toString`. Check if the name is either toJSON or observers and to return the actual target and content key if it exists. This seems to fix the issue.
> Fix for Delete ajax maximum call stack exceeded

- package.json
- src/flow/journey.js
- src/session/index.js
- test/flow/journey.test.js
In CNP we cannot get the correct url when on preview-staging environment, for this reason sessions are failing to be created successfully.
This PR uses the requested hostname to set the correct url.
> set cookie domain based on request

- examples/test-app/app.js
- examples/test-app/config/default.yml
- examples/test-app/yarn.lock
- package.json
- src/flow/journey.js
- test/errors/errorPages.test.js
- test/flow/journey.test.js
- test/util/supertest.js
Given the cookie domain is now set by the request (https://github.com/hmcts/one-per-page/pull/140) there is no need for a base Url on one-per-page.
Also added new config options to test app
> Remove baseUrl

- package.json
- src/i18n/contentProxy.js
- test/i18n/contentProxy.test.js
need to return full object to enable iterating through nested objects.
Used in the latest @hmcts/one-per-page-test-suite
> Return nested keys

- package.json
- src/i18n/loadStepContent.js
- test/i18n/fixtures/loadStepContent/StepName.content.section.json
- test/i18n/loadStepContent.test.js
As part of DIV-3266 changing the folder structure to accomodate different stages of content, so creating content subfolder to segregate content in different files. OPP has to load content sub folder and those changes are included in this PR.
> Adding content sub folder to track diff stages content

- package.json
- src/middleware/loadStepContent.js
- src/steps/Page.js
- test/middleware/loadStepContent.test.js
For some reason promises are failing to load content occasionally on AAT.
This PR moves content loading to middleware.
> Use middleware to load content
